version: "3.9"
services:
  tfserving:
    image: intel/intel-optimized-tensorflow-serving:2.3.0
    ports:
      - "8500:8500"
      - "8501:8501"
    volumes:
      - ./tmp/model:/models/rfcn
    environment:
      TENSORFLOW_INTER_OP_PARALLELISM: 2
      TENSORFLOW_INTRA_OP_PARALLELISM: 2
      MODEL_NAME: rfcn
      OMP_NUM_THREADS: 2
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432

    environment:
      &postgres_envs
      POSTGRES_USER: username # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: default_database

  webapp:
    build: .
    ports:
      - "5000:5000"
    environment:
      <<: *postgres_envs
      TFS_HOST: tfserving
      TFS_PORT: 8501
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: prod_counter
      DB_ENGINE: postgres
      POSTGRES_HOST: postgres
      ENV: prod
    volumes:
      - ./:/app/
