version: "3.9"
services:
  tfserving:
    image: intel/intel-optimized-tensorflow-serving:2.3.0
    ports:
      - "8500:8500"
      - "8501:8501"
    volumes:
      - ./tmp/model:/models/
    env_file:
      - .env
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432

    env_file:
      - .env

  webapp:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./:/app/
